### ISSUE TITLE
Truncated display for "Ne Sait Pas"

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Drama-Queen#110]
On most of cases, the text for "Ne Sait Pas" if truncated 👇 

![image](https://github.com/InseeFr/Drama-Queen/assets/1663283/2c5507ff-bc79-4c8f-aa76-3714911befc8)

**Comment by QRuhier** [comment]
already done with orchestrator refactor, waiting for being deployed

**Comment by romaintailhurat** [comment]
Indeed, OK with 2.0.0-rc1
