### ISSUE TITLE
Possibilité de passer un checkboxGroup sans réponse ni NSP et Refus suite à un retour arrière

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Drama-Queen#112]
Il est possible de "passer" une QCM sans réponse, ni NSP ou Refus suite à un retour arrière suivi de la désélection des modalités précédemment renseignées dans Queen.

=> On est sur un QCM, on coche des modalités, on passe à la question d'après, on revient en arrière, on décochesles modalités : on s'attend à ne pas pouvoir passer sans faire un NSP/refus ou recocher mais en fait, on peut.

**Comment by QRuhier** [comment]
Derrière ça il y a 2 sujets :

- dans une QCM, si tu coches puis décoches, le bouton "Continuer" reste présent donc tu peux passer à vide
- dans tous les input qu'on peut remettre à vide (QCM, input, inputNumber...) , si tu reviens en arrière tu peux toujours effacer ta réponse et ravancer (suite de l'entretien, suivant...)
