### ISSUE TITLE
Refactor validation

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Drama-Queen#119]
Quentin has produced a new version of Drama-Queen (see [this](https://hackmd.io/tbSs8yNNTNu4mn15bR1ygg)) that we need to validate.

**Comment by romaintailhurat** [comment]
@ddecrulle @laurentC35 we will need it to be deployed on a validation platform

**Comment by AnneHuSKa** [comment]
Retours validés dans le document.

Questions : 
- [ ]  ![image](https://github.com/InseeFr/Drama-Queen/assets/71011059/c5bb42c1-2cbe-4a82-a84b-a65b2ccb0610) : affichage du titre de sous-séquence en cas de boucle principale ? On peut garder ainsi car la répétition du  libellé occupait beaucoup de place

**Comment by QRuhier** [comment]
Pas volontaire pour le titre de sous-seq (j'ai le bon affichage en local), si vous voyez d'autres affichages anormaux je ferai un fix groupé ^^

**Comment by romaintailhurat** [comment]
See #132

**Comment by QRuhier** [comment]
@romaintailhurat those 2 subjects were already before refactor (lunatic related subjects).
I propose to dissociate them from refactor validation and handle them later

**Comment by romaintailhurat** [comment]
Seems reasonable

**Comment by QRuhier** [comment]
> affichage du titre de sous-séquence en cas de boucle principale


fix with 2.0.0-rc.17
