### ISSUE TITLE
remove fastForward button + overview only navigating backward

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Drama-Queen#129]
short-term version of https://github.com/InseeFr/Drama-Queen/issues/174

- remove fastForward, but let possibility of returning when user left when he opens the questionnaire
- menu navigation : seq/subseq must be clickable only if its first page is before the current page

**Comment by QRuhier** [comment]
lunatic-related subject, to discuss

**Comment by AnneHuSKa** [comment]
Proposition :
-	Modifier le principe "Suite de l’entretien" en "Dernière page accédée", uniquement proposé à l’ouverture du questionnaire
-	Navigation latérale vers l’arrière uniquement
-	Renommer "suite de l’entretien" en « Dernière page accédée » (sauf si vous avez mieux ?)

**Comment by QRuhier** [comment]
- after discussing : see for removing fastforward button, replaced by a modal (like for Stromae) when entering the questionnaire

- also change navigation using overview : item should be reachable only if its page is before current page

**Comment by QRuhier** [comment]
for overview : see https://github.com/InseeFr/Lunatic/issues/1054

**Comment by QRuhier** [comment]
@AnneHuSKa @romaintailhurat in the end we would have for now :

# currentPage

instead of saving lastReachedPage as the surveyUnit currentPage, we save the current page (like Stromae)

# fastForward

We remove the fastForward button.

We add a modal entering the questionnaire (similar as Stromae) for going back where user left :
- modal is not present on readonly (review, visu)
- modal is only present if the currentPage existed and was not the first page
- one button for returning to 1st page, one button for going back to currentPage (page on which the user was before he left)

# menu (overview)

We can only navigate to a seq/subseq which first page <= the current page (before it was compared to the lastReachedPage)

**Comment by AnneHuSKa** [comment]
@QRuhier : it seems very clear et I think it is ok. 
We will mention the last "be careful" to MOAE.

**Comment by AnneHuSKa** [comment]
- [x] we remove the fastForward button.
- [x] We add a modal entering the questionnaire (similar as Stromae) for going back where user left :
- [x] modal is not present on readonly (review, visu)
- [x] modal is only present if the currentPage existed and was not the first page
- [x] one button for returning to 1st page, one button for going back to currentPage (page on which the user was before he left)
- [x] We can only navigate to a seq/subseq which first page <= the current page

ok !
