### ISSUE TITLE
`F2` / `F4` shorcuts are not working for simple choice with a dropdown

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Drama-Queen#133]
When on page with a simple choice with a dropdown, you can't directly use the `F2` / `F4` shorcuts, they will only work when the focus is not on the dropdown itself.

**Comment by QRuhier** [comment]
Same as for suggesters, lunatic subject.
Only difference for dropdown is that currently the autofocus is set on the dropdown (and directly open) ; for suggester the autofocus is set on DK button so you can use shortcuts when arriving on the page (missing, previous, next...)
