### ISSUE TITLE
Upgrade to lunatic 3.0

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Drama-Queen#152]
Upgrading Lunatic from 2.7 to 3.0

- handle loops in menu : #93
- refactor breadcrumb using overview
- recreate all the style for lunatic components (Q/A area), not using lunatic default style anymore
  - also add style for components that were not handled : duration

**Comment by QRuhier** [comment]
main things to check : 
- navigation menu (sequence/subsequence)
- suggesters
- all the style of Q/A area

**Comment by romaintailhurat** [comment]
Checks - WIP:

- [ ]  navigation menu (sequence/subsequence)
- [ ] breadcrumb
- [ ] suggesters
- [ ]  autoNext when selecting radio/checkboxOne/missing
- [ ]  all the style of Q/A area (for every lunatic component) that has been recreated since we don't import default Lunatic style anymore
