### ISSUE TITLE
Questionnaires qui parlent : prise en compte avec Drama-Queen 2.x

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Drama-Queen#194]
## Description

Reprendre les travaux faits sur Drama-Queen 1.x, dans la version 2.x, pour permettre le fonctionnel des questionnaires qui parlent (Gide)

## Coûts en points

Estimé lors d'un poker planning: __22 pts__.

Les points sont répartis dans les tâches suivantes:

### Tâches @laurentC35 

- [x] #231
- [x] #233
- [x] #235
- [x] #238
- [x] #240
- [x] #242
- [x] #243

Estimation de 4/5 jours de développement "plein" sur le sujet (1pt = 0.5 jour)

### Tâches @QRuhier 

- [x] #241
- [x] #239
- [x] #237
- [x] #236
- [x] #232

Estimation de 7/8  jours de développement "plein" sur le sujet (1pt = 0.5 jour)

### Tâches communes

- [x] #234

**Comment by JulienCarmona** [comment]
Duplicate of 
- https://github.com/InseeFr/Concevoir-Workplace/issues/2
