### ISSUE TITLE
Absence des déclarations pour les réponses DropDown & suggester

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Drama-Queen#207]
Les déclarations CAPI ou CATI ne sont pas affichées quand on a une réponse de type Dropdown

[Issue_declarations_dropdown.json](https://github.com/user-attachments/files/16759702/Issue_declarations_dropdown.json)

**Comment by QRuhier** [comment]
see lunatic : https://github.com/InseeFr/Lunatic/issues/1148
