### ISSUE TITLE
[Talking Survey] vérifier le stockage actuel des data dans le cache

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Drama-Queen#243]
Vérifier que depuis Drama-Queen 2.0 le path du cache pour les surveyUnit correspond toujours à celui utilisé par l'application Gide

**Comment by laurentC35** [comment]
@QRuhier tu as déjà regardé de ton côté ?

**Comment by laurentC35** [comment]
Vu avec @QRuhier, l'interface de stockage via indexdb des surveyUnit n'a pas changée.

Cette issue est donc done
