### ISSUE TITLE
Synchro 💥 when trying to put a survey-unit that does not exist

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Drama-Queen#247]
# Description
During synchronization, when trying to put a survey-unit, if it does not succeed, the synchronization stops failing. When doing synchro again, the problem remains. So we don't even put the other survey-units, and we don't get any

# Expected behaviour

If it does not succeed in putting a survey-unit, this SU should be sent im tempzone, and the synchro should keep going

# Criticity : Critical

**Comment by QRuhier** [comment]
⚠️ also needs a version of queen-api >= 4.3.18 or <=3.5.47
Between those versions, the post surveyUnit in temp-zone does not work, so the synchro would still 💥in this usecase

**Comment by JulienCarmona** [comment]
@QRuhier pour la validation de ce ticket, il suffit de demander à Collecter si le correctif fonctionne bien ?
Ou on a des choses à faire de notre côté aussi ?

**Comment by QRuhier** [comment]
@JulienCarmona Pour la partie synchro pour le moment on déporte la responsabilité au métier de Collecter (avec une grosse vérification côté info chez nous du coup)
