### ISSUE TITLE
Check box not displayed in tab

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Drama-Queen#264]
# Issue initial
> Dans l’enquête Structures pour SD, nous avions créé des tableaux sous Pogues pour recueillir les créneaux d’ouverture. Cela fonctionnait bien, mais à présent, les cases à cocher n’apparaissent plus lors des visualisations sous Pogues ou Public Enemy. Nous n’avons pas encore tester sous Sabiane, mais comme il va nous falloir intégrer maintenant pour l’enquête de mise à jour, je voulais savoir s’il y a quelque chose à changer en raison d’une modification des outils qui aurait pu avoir lieu depuis la création du questionnaire ? Ou sinon, quelle peut-être la source du problème ?

Questionnaire :PROD - m2oo894q
Exemple de question : AJ_CRENOUV

# reproduction 
### Bug (Queen)
![Image](https://github.com/user-attachments/assets/8b5e2f52-266e-4f36-b5c2-667bda04de8a)

### Expected Behavior (⚠ Web -> Different Style)
![Image](https://github.com/user-attachments/assets/43c86577-7e8f-4412-8daf-a01b3910b3dc)

### Survey
Env: PROD
Survey: m3329tzd

**Comment by QRuhier** [comment]
Depuis Lunatic v3, Lunatic n'exporte plus de css par défaut.
Aujourd'hui puisqu'on assumait qu'on ne gérait pas de tableau dans Queen, il manque la majorité de la css des composants dans les tableaux.

On va gérer ce cas précis (checkbox boolean) vu l'urgence, mais ils serait important de faire une étude complète des manques liés aux tableaux si on décide de les gérer

**Comment by JulienCarmona** [comment]
# Validation QF  

App | Versions
-- | --
Pogues | [1.7.3-rc.4](https://github.com/InseeFr/Pogues/releases/tag/1.7.3-rc.4)
Queen | [2.3.0-rc.2](https://github.com/InseeFr/Drama-Queen/tree/v2.3.0-rc.2)
Pogues Back Office | [x](https://github.com/InseeFr/Pogues-Back-Office/tree/x)
stromae-dsf | [1.2.3](https://github.com/InseeFr/stromae-dsfr/tree/v1.2.3)
Lunatic | [3.4.3](https://github.com/InseeFr/Lunatic/tree/3.4.3)

## Résultats ✅ 
![Image](https://github.com/user-attachments/assets/60ec5ece-4fff-41ec-b642-5e2c04262417)

Les données sont également bien collectées
