### ISSUE TITLE
Problem when using filter

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Drama-Queen#44]
See details here :

> On a un souci surprenant sur des filtres dans tout le questionnaire sur les équipements. Certains semblent bien fonctionner d’après la visualisation dans Pogues, mais ils posent problème aussi bien à la visualisation Queen que sur le questionnaire enquêteur sous Sabiane. La variable de fin de filtre est posée alors qu’elle ne devrait pas. 
Des modifications du questionnaire ont été mises en œuvre pour rendre la programmation encore plus dans les règles de l’art, mais rien n’y fait. C’est un filtre qui est répété de nombreuses fois, donc le problème est important. Et encore plus étonnant, dans deux cas tout fonctionne bien, y compris sous Sabiane. Alexandre a regardé, mais nous ne trouvons pas d’explication. La bonne nouvelle c’est que, comme c’est toujours le même filtre, on peut raisonnablement espérer qu’une fois que le problème sera résolu sur un des filtres ce sera réglé pour tous...

**Comment by AnneHuSKa** [comment]
Existence du parser donc comportement différent visu POgues et Intégration
