### ISSUE TITLE
Mise à jour du Queen de conception

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Drama-Queen#58]
Bug signalé mais qui est corrigé depuis juillet (Queen 1.0.7). Vérifié sur Sandbox.

Versions en conception : Queen : 1.0.2 | Lunatic : 2.4.5-beta
Versions sur sandbox : Queen : 1.0.9 | Lunatic : 2.5.0-fix-last-reached-page

**Comment by romaintailhurat** [comment]
Recette en cours de Queen : 1.1.7 | Lunatic : 2.7.9
