### ISSUE TITLE
No auto focus on response field in Queen 1.1.0 Lunatic 2.7.3

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Drama-Queen#65]
The auto focus is done in pure Lunatic (checked with the [2.7 storybook](https://inseefr.github.io/Lunatic/storybook-2.7/)) but it doesn't work once integrated in Queen.

**Comment by laurentC35** [comment]
Fix with: https://github.com/InseeFr/Drama-Queen/pull/66
