### ISSUE TITLE
Add runtime variable for surveyUnitID

### ISSUE THREAD

**Issue by bwerquin** [InseeFr/Drama-Queen#67]
Is it possible to add a variable (or object of variables) similar to the GLOBAL_ITERATION_INDEX variable available in the runtime, with the value of the surveyUnit identifier so that it can be manipulated in a Markdown formula like the other variables in the questionnaire? This variable could be valued by the orchestrator using the pathParam, for example.

**Comment by laurentC35** [comment]
A solution suggested by @Grafikart is to let the orchestrator adding dynamical, EXERNAL variables to the questionnaire.json

**Comment by laurentC35** [comment]
Variables allowed will be name as :
- `SURVEY_UNIT_ID` (string type)
- `QUESTIONNAIRE_ID` (string type)

**Comment by laurentC35** [comment]
closed with #68
