### ISSUE TITLE
App is crashing when it gets to a table response

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Drama-Queen#74]
# Description of the issue

> Queen : 1.1.2 | Lunatic : 2.7.4

Questions that hold a table crash (white page).

This error does occur in pure Lunatic

# How to reproduce

Simply by checking [this questionnaire](https://visu-queen-v2-sandbox.demo.insee.io/queen/visualize?questionnaire=https%3A%2F%2Fminio.lab.sspcloud.fr%2Fromaintailhurat%2Fpublic%2Fbowie%2FQnonregSimpson-LunaticCapi.json). The source [is here](https://github.com/InseeFr/Bowie/blob/main/useful-questionnaires/validation/QnonregSimpson-LunaticCapi.json).

More details [here](https://hackmd.io/4UgeQrgwQI67BWZdmePWyA#811).

**Comment by ddecrulle** [comment]
This should be fixed by #72

**Comment by romaintailhurat** [comment]
It is in 1.1.8!
