### ISSUE TITLE
Weird behaviour of text inputs in a non paginated loop

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Drama-Queen#86]
In Queen : 1.1.6 | Lunatic : 2.7.9

When typing in the second field, after the first character is added, we jump to the first input field. In the following example, we want to write "ABCD" in the 1st field and "EFGH" in the 2nd:

![image](https://github.com/InseeFr/Drama-Queen/assets/1663283/4ccacfcd-05f4-4a14-9c4a-0a046f51d689)

This bad behaviour doesn't exist in pure Lunatic.

__How to reproduce__

Simple test questionnaire

[test-questionnaire-drama-queen-86.zip](https://github.com/InseeFr/Drama-Queen/files/13612431/test-questionnaire-drama-queen-86.zip)

**Comment by romaintailhurat** [comment]
@Grafikart will take a quick look at the issue

**Comment by Grafikart** [comment]
@romaintailhurat Comment je lance la version 1.1.6 ? 

Je suis branché sur main et si je lance queen il me dit 0.10.20 :(

**Comment by romaintailhurat** [comment]
Absolutely no idea 😞 

Need to ask @ddecrulle
