### ISSUE TITLE
Numeric fields with a `0` value prevent the dispay of the "Continue" button

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Drama-Queen#89]
> Queen : 1.1.7 | Lunatic : 2.7.9

__Description__

Numeric fields, even when allowing a minimum value of `0`, prevent the "Continue" button to be displayed.

__How to reproduce__

With this  simple questionnaire.

[lq10ncwl.json](https://github.com/InseeFr/Drama-Queen/files/13637869/lq10ncwl.json)

**Comment by laurentC35** [comment]
Perhaps it has something to do with the fact that 0 and null are managed in the same way?

**Comment by laurentC35** [comment]
Issue Lunatic

**Comment by laurentC35** [comment]
closed, duplicated : https://github.com/InseeFr/Lunatic/issues/831
