### ISSUE TITLE
A sub-sequence without a question doesn't display the "Continue" button

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Drama-Queen#90]
Though it's not a good practice, some questionnaires can provide a sub-sequence that doesn't contain a question. In Queen 1.1.8, this leads to a page without any "Continue" button which is problematic.

**Comment by laurentC35** [comment]
Je n'ai pas réussi à reproduire le bug, c'est possible d'avoir un questionnaire dans l'issue dans lequel se produit le bug ?
Merci
