### ISSUE TITLE
Navigation panel (aka Overview) is missing sequences when they are part of a Loop

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Drama-Queen#93]
# Description

Some questionnaires provide a broken left navigation panel with missing sequences, for example:

![image](https://github.com/InseeFr/Drama-Queen/assets/1663283/def53d6a-3ee0-4aae-9c06-df7da70a9a42)

> components III and IV are missing ☝️ 

It seems to occur for some special questionnaires using Pogues composition feature, but not all.

🔍 In the provided test questionnaire, we can also mention a maybe broken pairwise component in the second sequence.

# How to reproduce

Using the following questionnaire: [lpgqahah_lunatic.zip](https://github.com/InseeFr/Drama-Queen/files/13726465/lpgqahah_lunatic.zip)

**Comment by laurentC35** [comment]
Les titres de séquence qui manquent sont dans une boucle. C'est pourquoi elles n'apparaissent pas.
Il faudrait définir ce qu'on voudrait.
Par exemple.
On boucle sur un ensemble [Sequence, question1, question2], qu'est-ce qu'on souhaite affiché dans ce menu, le titre de la séquence bouclée ? Oui mais pour quelle occurrence du coup ?

Afficher dans le menu : Boucle XXX > Ocurences [0/1/2/..] > Sequence blaba ?

**Comment by romaintailhurat** [comment]
A minima, une première solution pour ajouter le nom des séquences sur lesquelles on boucle, avec comme lien principal le titre de la séquence qui amène au titre de la séquence sur la première itération.

On peut accompagner le titre d'un symbole signifiant qu'on est dans une boucle ?

![image](https://github.com/InseeFr/Drama-Queen/assets/1663283/1c5c1aa7-de5e-46d7-861d-b3fe50132735)

**Comment by laurentC35** [comment]
Please see https://github.com/InseeFr/Lunatic/issues/842

**Comment by romaintailhurat** [comment]
Avant qu'on soit dans la boucle initiale, on a de toute façon un problème puisqu'on a une valeur inexistante, donc on va afficher un libellé non exécuté (eg `Les activités de || PRENOM`).

Une fois qu'on a la valeur par contre, on peut décider de ce que l'on fait:

1. on affiche la première valeur de la variable (PRENOM devient Alice)
2. on affiche dynamiquement la valeur, celle de l'occurence actuelle de la boucle (PRENOM devient Alice, puis Bob, etc.)
3. on a un libellé alternatif dans Pogues 😲 

Préférence au 1 bien sûr dans l'immédiat.

**Comment by laurentC35** [comment]
Et pourquoi pas:
```
| - I Adresse
| - II Tableau des habitants du logement
|         - Boucle / Sous-séquénce répétées
|                  - SS1 d'Alice
|                  - SS1 de Bob
| - Boucle / Séquence répétée
|         - III Les activités d'Alice
|         - III Les activités de Bob
```

**Comment by romaintailhurat** [comment]
OK, je me restreint trop dans ce que j'imagine parce que je crois ça cher 😅

J'aime bien cette vision en tout cas

**Comment by AnneHuSKa** [comment]
Ah oui @romaintailhurat @laurentC35 ca serait top de top. Si pas cher car bon, ca reste du "confort" à mon sens, mais c'est beau !

**Comment by romaintailhurat** [comment]
Finalement, on retient ce fonctionnement (pour s'aligner sur le _Breadcrumb_)

```
| - I Adresse
| - II Tableau des habitants du logement
|         - SS1 d'Alice *
|         - SS1 de Bob *
| - III Les activités d'Alice **
| - III Les activités de Bob **
```

`*` Itérations d'une boucle de sous-séquence
`**`  Itérations d'une boucle de séquence
